##### PREFIX ############################################################

unbind C-b
set -g prefix C-Space
bind C-Space send-prefix


##### GENERAL SETTINGS ##################################################

run-shell '
  shell=$(command -v fish || command -v zsh || command -v bash)
  tmux set -g default-shell "$shell"
'
set -g mouse on
set -g history-limit 200000
set -g renumber-windows on
set -g status-position top
setw -g automatic-rename on
set-option -g detach-on-destroy off

bind r source-file $HOME/.config/tmux/tmux.conf \; display-message "Reloaded tmux.conf"
bind R source-file $HOME/.config/tmux/tmux.conf \; display-message "Reloaded tmux.conf"
bind o display-popup -b rounded -w 80% -h 80% -E "$HOME/Code/scripts/sessions.sh"
bind g display-popup -b rounded -w 80% -h 80% -E "lazygit"

# NOTE: This is useful for debugging.
# set -g remain-on-exit on


##### TERMINAL & COLOR (Kitty optimized) ################################

set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",xterm-kitty:RGB"
set -g focus-events on


##### COPY MODE & SYSTEM CLIPBOARD ######################################

setw -g mode-keys vi
set -g set-clipboard on

bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send -X copy-selection-and-cancel


##### TPM (Plugin Manager) ##############################################

set-environment -g TMUX_PLUGIN_MANAGER_PATH "$HOME/.local/share/tmux/plugins"

if "test ! -d $HOME/.local/share/tmux/plugins/tpm" "run 'git clone https://github.com/tmux-plugins/tpm $HOME/.local/share/tmux/plugins/tpm && $HOME/.local/share/tmux/plugins/tpm/bin/install_plugins'"

set -g @plugin 'tmux-plugins/tpm'

# Core improvements
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-pain-control'

# Quick select text
set -g @plugin 'Morantron/tmux-fingers'
set -g @fingers-key C-space

# Status line
set -g @plugin 'thewtex/tmux-mem-cpu-load'
set -g @plugin 'erikw/tmux-powerline'

run "$HOME/.local/share/tmux/plugins/tpm/tpm"
