Diagnostics:
  ClangTidy:
    Remove: [readability-identifier-length, cppcoreguidelines-pro-type-reinterpret-cast, cppcoreguidelines-avoid-magic-numbers, readability-magic-numbers,bugprone-easily-swappable-parameters, cppcoreguidelines-pro-bounds-constant-array-index]
