# shellcheck shell=bash
# Default Theme
# If changes made here does not take effect, then try to re-create the tmux session to force reload.

TMUX_POWERLINE_SEPARATOR_LEFT_BOLD=""
TMUX_POWERLINE_SEPARATOR_LEFT_THIN=""
TMUX_POWERLINE_SEPARATOR_RIGHT_BOLD=""
TMUX_POWERLINE_SEPARATOR_RIGHT_THIN=""

TMUX_POWERLINE_WINDOW_SEPERATOR_LEFT=""
TMUX_POWERLINE_WINDOW_SEPERATOR_RIGHT=""

# See Color formatting section below for details on what colors can be used here.
TMUX_POWERLINE_DEFAULT_BACKGROUND_COLOR=${TMUX_POWERLINE_DEFAULT_BACKGROUND_COLOR:-'235'}
TMUX_POWERLINE_DEFAULT_FOREGROUND_COLOR=${TMUX_POWERLINE_DEFAULT_FOREGROUND_COLOR:-'255'}

TMUX_POWERLINE_DEFAULT_LEFTSIDE_SEPARATOR=${TMUX_POWERLINE_DEFAULT_LEFTSIDE_SEPARATOR:-$TMUX_POWERLINE_SEPARATOR_RIGHT_BOLD}
TMUX_POWERLINE_DEFAULT_RIGHTSIDE_SEPARATOR=${TMUX_POWERLINE_DEFAULT_RIGHTSIDE_SEPARATOR:-$TMUX_POWERLINE_SEPARATOR_LEFT_BOLD}

# shellcheck disable=SC2128
if [ -z "$TMUX_POWERLINE_WINDOW_STATUS_CURRENT" ]; then
  TMUX_POWERLINE_WINDOW_STATUS_CURRENT=(
    "$TMUX_POWERLINE_WINDOW_SEPERATOR_LEFT"
    "#[$(tp_format inverse)]"
    " #I#F "
    "$TMUX_POWERLINE_SEPARATOR_RIGHT_THIN"
    " #W "
    "#[$(tp_format regular)]"
    "$TMUX_POWERLINE_WINDOW_SEPERATOR_RIGHT"
  )
fi

# shellcheck disable=SC2128
if [ -z "$TMUX_POWERLINE_WINDOW_STATUS_STYLE" ]; then
  TMUX_POWERLINE_WINDOW_STATUS_STYLE=(
    "$(tp_format regular)"
  )
fi

# shellcheck disable=SC2128
if [ -z "$TMUX_POWERLINE_WINDOW_STATUS_FORMAT" ]; then
  TMUX_POWERLINE_WINDOW_STATUS_FORMAT=(
    "#[$(tp_format regular)]"
    "  #I#{?window_flags,#F, } "
    "$TMUX_POWERLINE_SEPARATOR_RIGHT_THIN"
    " #W "
  )
fi

# shellcheck disable=SC1143,SC2128
if [ -z "$TMUX_POWERLINE_LEFT_STATUS_SEGMENTS" ]; then
  TMUX_POWERLINE_LEFT_STATUS_SEGMENTS=(
    "tmux_session_info 24 255 ${TMUX_POWERLINE_SEPARATOR_RIGHT_THIN}"
    "hostname 24 255 ${TMUX_POWERLINE_SEPARATOR_RIGHT_THIN}"
    "lan_ip 24 255"
    "vcs_branch 22 255"
    "pwd 235 136 ${TMUX_POWERLINE_SEPARATOR_RIGHT_THIN}"
    "mode_indicator 235 136 ${TMUX_POWERLINE_SEPARATOR_RIGHT_THIN}"
  )
fi

# shellcheck disable=SC1143,SC2128
if [ -z "$TMUX_POWERLINE_RIGHT_STATUS_SEGMENTS" ]; then
  TMUX_POWERLINE_RIGHT_STATUS_SEGMENTS=(
    "disk_usage 235 136 ${TMUX_POWERLINE_SEPARATOR_LEFT_THIN}"
    "tmux_mem_cpu_load 235 136 ${TMUX_POWERLINE_SEPARATOR_LEFT_THIN}"
    "battery 235 136 ${TMUX_POWERLINE_SEPARATOR_LEFT_THIN}"
    "date 24 255"
    "time 24 255 ${TMUX_POWERLINE_SEPARATOR_LEFT_THIN}"
  )
fi
