return {
  -- { "AckslD/muren.nvim", opts = {} },
  -- { "Bekaboo/dropbar.nvim" },
  -- { "Borwe/wasm_nvim" },
  -- { "CKolkey/ts-node-action" },
  -- { "Konfekt/FastFold" },
  -- { "Olical/conjure" },
  -- { "RRethy/nvim-treesitter-textsubjects" },
  -- { "ThePrimeagen/refactoring.nvim", opts = {} },
  -- { "Zeioth/compiler.nvim" },
  -- { "akinsho/git-conflict.nvim" },
  -- { "bennypowers/nvim-regexplainer" },
  -- { "cbochs/grapple.nvim", dependencies = "nvim-lua/plenary.nvim" },
  -- { "cbochs/portal.nvim" },
  -- { "chrisgrieser/nvim-early-retirement", opts = {} },
  -- { "chrisgrieser/nvim-spider" },
  -- { "chrisgrieser/nvim-various-textobjs" },
  -- { "dccsillag/magma-nvim" },
  -- { "debugloop/telescope-undo.nvim" },
  -- { "f-person/git-blame.nvim" },
  -- { "folke/edgy.nvim" },
  -- { "frabjous/knap" },
  -- { "gbprod/substitute.nvim" },
  -- { "gbprod/yanky.nvim" },
  -- { "ghillb/cybu.nvim" },
  -- { "gorbit99/codewindow.nvim" },
  -- { "haya14busa/vim-asterisk" },
  -- { "iamcco/markdown-preview.nvim" },
  -- { "jamestthompson3/nvim-remote-containers" },
  -- { "jbyuki/instant.nvim" },
  -- { "justinmk/vim-dirvish" },
  -- { "kevinhwang91/nvim-hlslens" },
  -- { "kevinhwang91/nvim-ufo" },
  -- { "lewis6991/hover.nvim" },
  -- { "linty-org/readline.nvim" },
  -- { "luukvbaal/statuscol.nvim" },
  -- { "mbbill/undotree" },
  -- { "mg979/vim-visual-multi", branch = "master", opts = {} },
  -- { "mhinz/neovim-remote" },
  -- { "michaelb/sniprun" },
  -- { "miversen33/netman.nvim" },
  -- { "mrjones2014/legendary.nvim" },
  -- { "nacro90/numb.nvim" },
  -- { "nvim-pack/nvim-spectre" },
  -- { "p00f/godbolt.nvim" },
  -- { "renerocksai/telekasten.nvim" },
  -- { "roobert/search-replace.nvim" },
  -- { "smjonas/live-command.nvim" },
  -- { "stevearc/aerial.nvim" },
  -- { "sunjon/Shade.nvim" },
  -- { "tomiis4/hypersonic.nvim" },
  -- { "willothy/flatten.nvim" },
  -- { "ziontee113/syntax-tree-surfer" },
  -- {"Wansmer/sibling-swap.nvim"}
  -- {"akinsho/git-conflict.nvim"}
  -- {"altermo/ultimate-autopair.nvim"}
  -- {"anuvyklack/hydra.nvim"}
  -- {"axkirillov/easypick.nvim"}
  -- {"debugloop/telescope-undo.nvim"}
  -- {"echasnovski/mini.clue"}
  -- {"gabrielpoca/replacer.nvim"}
  -- {"m4xshen/hardtime.nvim"}
  -- {"mfussenegger/nvim-dap"}
  -- {"mfussenegger/nvim-lint"}
  -- {"nvim-neorg/neorg-telescope"}
  -- {"nvim-telescope/telescope-file-browser.nvim"}
  -- {"nvim-telescope/telescope-live-grep-args.nvim"}
  -- {"rcarriga/nvim-dap-ui"}
  -- {"rgroli/other.nvim"}
  -- {"simrat39/symbols-outline.nvim"}
  -- {"stevearc/conform.nvim"}
  -- {"stevearc/oil.nvim"}
  -- {"theHamsta/nvim-dap-virtual-text"}
  -- {"tpope/vim-dadbod"}
  -- {"tpope/vim-projectionist"}
  -- {"xeluxee/competitest.nvim"}
}
